### ISSUE TITLE
Error from bufferevent

### ISSUE THREAD

**Issue by JBelinchon** [droe/sslsplit#170]
Hi, I see a lot of error messages like those:

Error from bufferevent: 113:No route to host 0:0:-:0:-:0:-

Error from bufferevent: 0:- 336151574:1046:sslv3 alert certificate unknown:20:SSL 

I am using Raspi Stretch

Any clue?

**Comment by droe** [comment]
No route to host means exactly that, no route to host. Without full logs and specifics on NAT config and server, this is impossible to answer.

**Comment by MikaeloFlorentino** [comment]
have same problem

     _:sslv3 alert certificate unknown_

run thread 1
./sslsplit -k ca/ca.key -c ca/ca.crt -D https 0.0.0.0 8000 -L /tmp/connections.log -j /tmp/sslsplit/

run thread 2
ettercap -Tqi wlo1 -M arp /192.168.1.111// /192.168.1.254//

my client send request and sslsplis says

SNI peek: [domains.com] [complete]
Connecting to [192.168.1.111]:443
===> Original server certificate:
Subject DN: /CN=domains.com
Common Names: domains.com/domains.com/www.domains.com
Fingerprint: AB:7B:DD:D7:3D:B7:4B:80:D7:3893:2F:27:B9:0D:2C:95:30:E7:B5
Certificate cache: MISS
===> Forged server certificate:
Subject DN: /CN=domains.com
Common Names: domains.com/domains.com/www.domains.com
Fingerprint: 5F:B1:58:EF:D9:16:10:E3:9B:E122:7F:F7:E6:1A:B4:6B:48:62:4B
SSL connected to [192.168.1.111]:9454 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256
SSL session cache: MISS
Certificate cache: KEEP (SNI match or target mode)
**Error from bufferevent: 0:- 336151574:1046:sslv3 alert certificate unknown:20:SSL routines:148:ssl3_read_bytes**
SSL disconnected to [192.168.1.111]:443
SSL disconnected from [192.168.1.235]:52426
SSL_free() in state 00002190 = SSL_ST_ACCEPT|0190 = UNKWN  (unknown state) [accept socket]
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]

Garbage collecting caches started.
Garbage collecting caches done.

**Comment by droe** [comment]
From the log above it would seem that you are at least two releases behind; SSLsplit indicates the direction (src or dst) in bufferevent errors since release 0.5.1. Please retry using the latest release of `develop` branch. If that does not help, please open a new issue and provide all the information asked for in the template.

Note that "sslv3 alert certificate unknown" indicates that one of the peers, probably the client, is refusing the certificate presented by SSLsplit, which is expected unless you added the CA certificate to the client's trust store or configured an exception.
