### ISSUE TITLE
How to route traffic back to machine

### ISSUE THREAD

**Issue by yogi-dmt** [droe/sslsplit#176]
Is there an easy way to route traffic coming back to the sslsplit box, back to your machine? Or do you basically need to be running sslsplit on a router?

**Comment by droe** [comment]
Your question is unclear to me, please elaborate what exactly you want to achieve.

**Comment by yogi-dmt** [comment]
I was just reading some of the tutorials and they seem to route traffic from the client to a vm running sslsplit (and apparently you need to mirror the virtual port to read the packets which none of them mentioned) but they don't talk about how to route external traffic hitting the vm back to the client. My question is wouldn't you need to essentially run sslsplit on a router to look at a two way conversation?

**Comment by droe** [comment]
There are many ways to use sslsplit. Obviously, sslsplit needs to have network connectivity to both upstream and downstream peers, and it needs to be able to ask the kernel for the original destination IP of incoming connections. The easiest and most common way to achieve this is to run it on a router/gateway/ap, but it is not the only way. You should contact the author(s) of the tutorials you are referring to in order to clarify how their setup is intended to work.
