### ISSUE TITLE
Generic -o option to override config file options

### ISSUE THREAD

**Issue by droe** [droe/sslsplit#200]
It would be good to have a generic `-o` command line facility to override configuration statements and allow command line configuration of all configuration statements. Like `-o VerifyPeer=yes`. That would compensate for not exposing some config file options to the command line interface, such as in #199.

**Comment by sonertari** [comment]
I think this is doable, but looks a bit tricky to me:

1. Currently, I apply conf file options after all command line options are processed, meaning that the settings in the conf file have precedence over those on the command line. To achieve the otherwise, I should move the load_conffile() to the case statement for the -f option.
2. However, with the change I suggest in my first point, the order of the -f option on the command line will be important: -f should always be the first option passed if the user wants to override the options in it. Otherwise, using -f as, for example, the last option will bring us back to the current situation.
3. On second thought, the behavior achieved after my suggested change in my first point may have desirable benefits, because now the user can choose the precedence of command line or conf file options, by moving the -f option up or down as he wishes.
4. On the other hand, if we are to force the precedence of individual options strictly in the code, i.e. we don't leave any flexibility to the user, then the changes required to achieve that seem more involved to me: We need to accumulate all options in a struct first, and then apply precedence before processing.
5. I think it should not be possible to override certain options, such as ProxySpec. Otherwise may be unnecessarily involved, imo: We should search if the new proxyspec conflicts with an already existing proxyspec, and then delete the old one and clean up.
6. To support -o name=value facility, I need to refactor the while loop in load_conffile() to be able to feed the name-value pair to the same logic, which seems doable.

As a more general note, I am for keeping things as simple as possible, and expecting users to know what they are doing. Otherwise, they can do interesting stuff. For example, they can choose one nat engine and apply related proxy specs first, and then switch to another nat engine and apply other proxy specs. I am not sure if this would be a useful feature, or would cause unintended complications (note that since the proxyspec struct has a natengine field, and we have the -f option now, this is already possible on the develop branch).

Any comments? Otherwise, I can implement something, so we can discuss over working software.

**Comment by droe** [comment]
I handle this in [xnumon](https://github.com/droe/xnumon/blob/develop/xnumon.c) by having a first getopt() call handling only loading the config file, then using `optreset = 1; optind = 1;` to reset getopt, and then a second getopt() call to handle all the other options. It's not pretty because both switch statements need to handle all the letters, but except for the case statements no code is duplicated and it avoids most of the above problems. Of course the loading of the conf file needs to have a function that takes options as key/value pairs instead of from a file.
