### ISSUE TITLE
SSLsplit as browser's HTTP proxy: Error 24 on listener: Too many open files

### ISSUE THREAD

**Issue by Simon45** [droe/sslsplit#93]
Has anyone had success running sslsplit on Ubuntu 14?

When I start sslsplit and try connecting to it from a browser (root cert is loaded in browser and proxy is also set to point to the IP running sslsplit), sslsplit terminates with error below.
Browser and sslsplit are running on separate physical machines

///////////////
Ubuntu 14.10
Linux cnroot 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Error is as below.

    tcp [10.11.1.7]:55367 [10.11.1.7]:8080
    Connecting to [10.11.1.7]:8080
    tcp [10.11.1.7]:55368 [10.11.1.7]:8080
    Connecting to [10.11.1.7]:8080
    tcp [10.11.1.7]:55369 [10.11.1.7]:8080
    Connecting to [10.11.1.7]:8080
    tcp [10.11.1.7]:55370 [10.11.1.7]:8080
    tcp [10.11.1.7]:55371 [10.11.1.7]:8080
    Connecting to [10.11.1.7]:8080
    Error 24 on listener: Too many open files
    Main event loop stopped.

Setup is as below.
client laptop -----------  sslsplit  server --------- Internet

iptables has only 2 entries and I do not see any routing loops in iptables.

     # sudo iptables -t nat -L
     target     prot opt source               destination         
     REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http redir ports 8080
     REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 8080
     Chain INPUT (policy ACCEPT)
     target     prot opt source               destination         
     Chain OUTPUT (policy ACCEPT)
     target     prot opt source               destination         
     Chain POSTROUTING (policy ACCEPT)
     target     prot opt source               destination  

Any help is appreciated

**Comment by scotloach** [comment]
You're looping your traffic back through sslsplit again and again until it runs out of sockets, because the redirect rules are also working on the outbound connection from sslsplit.

Add an input interface so that only inbound connections are sent to sslsplit, e.g. if your LAN facing interface is eth0 and your WAN facing interface is eth1,
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080

**Comment by Simon45** [comment]
The appliance which is serving as the proxy has only 1 interface eth7, (connected to a switch that has its uplink to WAN). The client is also connected to the same switch on another port and has the proxy set in its browser settings to that of the appliance running sssplit

I did setup rules like so:
sudo iptables -t nat -A PREROUTING -i eth7 -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -i eth7 -p tcp --dport 443 -j REDIRECT --to-port 8080

**Comment by droe** [comment]
You need to exclude connections from sslsplit itself from the REDIRECT to prevent the endless loop, e.g. add `-s ! 10.11.1.7` into your iptables invocations.

**Comment by Simon45** [comment]
Still the exact same error. 

~/sslsplit-0.4.7$ sudo iptables -L -t nat
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  -- !10.11.1.7            anywhere             tcp dpt:http redir ports 8080
REDIRECT   tcp  -- !10.11.1.7            anywhere             tcp dpt:https redir ports 8080

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

**Comment by droe** [comment]
Please post the exact command line you invoke sslsplit with, and how you make your client system send its traffic to your single-homed sslsplit server.

Also, while at this point I think your issue is purely about usage and not related to the version of sslsplit, note that 0.4.7 is quite dated. You might want to try 0.4.11 or even the latest `develop` branch.

**Comment by Simon45** [comment]
It is a very basic setup.

Client Browser  - - - - - > Router - - - - - > Internet
10.11.1.15                        |
Browser:FireFox              |
Explicit Proxy setup         | 
in the browser                  |
(picture attached)             |
                                        V
                                    sslsplit
                                    10.11.1.7    						  

Application is run with this:
sudo ./sslsplit -D -l connections.log -j /tmp/sslsplit/ -S logdir -k ca.key -c ca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080

sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  -- !10.11.1.7            anywhere             tcp dpt:http redir ports 8080
REDIRECT   tcp  -- !10.11.1.7            anywhere             tcp dpt:https redir ports 8443

Error seen:

SNI peek: [n/a] [complete]
Connecting to [10.11.1.7]:8443
SNI peek: [n/a] [complete]
Connecting to [10.11.1.7]:8443
SNI peek: [n/a] [complete]
Connecting to [10.11.1.7]:8443
SNI peek: [n/a] [complete]
Connecting to [10.11.1.7]:8443
SNI peek: [n/a] [complete]
Connecting to [10.11.1.7]:8443
Error 24 on listener: Too many open files
Main event loop stopped.
Error from bufferevent: 104:Connection reset by peer 0:0:-:0:-:0:-

![image](https://cloud.githubusercontent.com/assets/6722046/7387199/255411d6-ee10-11e4-88ab-0c267b9c1e62.png)

**Comment by droe** [comment]
Ah that explains it. SSLsplit is a transparent proxy only. It does not speak the HTTP proxy or SOCKS proxy protocols, so it cannot be configured to be an explicitly configured proxy. I may have to clarify that better in the docs.

Your options include configuring your sslsplit server as default gateway of the client instead of configuring it as a proxy in the browser. If you want to explicitly configure it in the browser, you may be better off using Paros, ZAP, Burp et al.

**Comment by droe** [comment]
Closing this issue; see #94 for possibly adding explicit proxy support.
